version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
      - match:
          dependency_type: "indirect"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
      prefix_development: "chore"
      include_scope: true